# Generated by Django 5.2.5 on 2025-08-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Сourse",
            new_name="Course",
        ),
    ]
