# Generated by Django 5.2.5 on 2025-08-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_rename_сourse_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
