name: Django CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run lint inside Python 3.13 container
        uses: addnab/docker-run-action@v3
        with:
          image: python:3.13
          options: --entrypoint ""
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --no-root
      - name: Run Flake8
        run: |
          poetry run flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: training
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 15111983
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run tests inside Python 3.13 container
        uses: addnab/docker-run-action@v3
        with:
          image: python:3.13
          options: --entrypoint ""
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --no-root
      - name: Run tests
        run: |
          poetry run python manage.py test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hab:${{ github.sha }} .
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hab:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          docker push ${{ secrets.DOCKER_USERNAME }}/hab:${{ github.sha }}
          docker stop hab || true
          docker rm hab || true
          docker run -d --name hab -p 80:8000 ${{ secrets.DOCKER_USERNAME }}/hab:${{ github.sha }}
          EOF