name: Django CI/CD

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ secrets.NAME }}
          POSTGRES_USER: ${{ secrets.USER }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    env:
      PYTHON_VERSION: 3.13
      NAME: ${{ secrets.NAME }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      HOST: ${{ secrets.HOST }}  # или localhost
      PORT: ${{ secrets.PORT }}  # например, 5432
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h $HOST -p $PORT; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Make migrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          NAME: ${{ secrets.NAME }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            echo "Starting deployment..."
            cd ${{ secrets.DEPLOY_DIR }}
            git pull origin main
            # тут ваши команды перезапуска сервиса или контейнера
          EOF